name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Flutter Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Install dependencies
      run: flutter pub get

    - name: Setup .env
      run: echo "APIKEY=${{ secrets.APIKEY }}" > .env

    - name: Run tests
      run: flutter test
